CREATE OR REPLACE TRIGGER prevent_insert_all_workers_elapsed
INSTEAD OF INSERT ON ALL_WORKERS_ELAPSED
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'Direct insertions into ALL_WORKERS_ELAPSED are not allowed.');
END;

CREATE OR REPLACE TRIGGER audit_robot_insert
AFTER INSERT ON ROBOTS
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_ROBOT (robot_id, created_at)
    VALUES (:NEW.id, SYSDATE);
END;
